spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show-sql: true
      format_sql: true
      use_sql_comments: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/jwt
    username: jwt
    password: password

## mus
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache